# Generated by Django 2.1.7 on 2019-04-08 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=20)),
                ('next_date_of_hearing', models.DateField()),
                ('file', models.FileField(null=True, upload_to='files/casefiles/')),
                ('peshi', models.FileField(null=True, upload_to='files/peshi/')),
                ('matter', models.CharField(default='N.A.', max_length=30)),
                ('petitioner_advocate', models.CharField(default='N.A.', max_length=30)),
                ('respondant_advocate', models.CharField(default='N.A.', max_length=30)),
                ('case_type', models.CharField(choices=[('SUPPLEMENTARY', 'Supplementary'), ('ADVANCE', 'Advance')], default='SUPPLEMENTARY', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CaseLaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('file', models.FileField(null=True, upload_to='files/caselaws/')),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourtRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Court')),
            ],
        ),
        migrations.CreateModel(
            name='CourtStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('court_staff', models.ManyToManyField(to='app.CourtStaff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Legislature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('file', models.FileField(null=True, upload_to='files/legislatures/')),
            ],
        ),
        migrations.CreateModel(
            name='LR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('view_peshi', models.BooleanField(default=False)),
                ('edit_peshi', models.BooleanField(default=False)),
                ('edit_casefile', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='lr',
            name='permissions',
            field=models.ForeignKey(default='LR', on_delete=django.db.models.deletion.CASCADE, to='app.Permission'),
        ),
        migrations.AddField(
            model_name='lr',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judge',
            name='lr',
            field=models.ManyToManyField(to='app.LR'),
        ),
        migrations.AddField(
            model_name='judge',
            name='permissions',
            field=models.ForeignKey(default='JUDGE', on_delete=django.db.models.deletion.CASCADE, to='app.Permission'),
        ),
        migrations.AddField(
            model_name='judge',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courtstaff',
            name='permissions',
            field=models.ForeignKey(default='CS', on_delete=django.db.models.deletion.CASCADE, to='app.Permission'),
        ),
        migrations.AddField(
            model_name='courtstaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courtroom',
            name='judges',
            field=models.ManyToManyField(to='app.Judge'),
        ),
        migrations.AddField(
            model_name='casefile',
            name='case_laws',
            field=models.ManyToManyField(to='app.CaseLaw'),
        ),
        migrations.AddField(
            model_name='casefile',
            name='court_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CourtRoom'),
        ),
        migrations.AddField(
            model_name='casefile',
            name='legislatures',
            field=models.ManyToManyField(to='app.Legislature'),
        ),
    ]
