# Generated by Django 2.1.7 on 2019-04-04 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('next_date_of_hearing', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CaseLaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('case_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CaseFile')),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourtRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Court')),
            ],
        ),
        migrations.CreateModel(
            name='CourtStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('court_staff', models.ManyToManyField(to='app.CourtStaff')),
            ],
        ),
        migrations.CreateModel(
            name='Legislature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('case_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CaseFile')),
            ],
        ),
        migrations.CreateModel(
            name='LR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('view_peshi', models.BooleanField(default=False)),
                ('edit_peshi', models.BooleanField(default=False)),
                ('edit_casefile', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='lr',
            name='permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Permission'),
        ),
        migrations.AddField(
            model_name='judge',
            name='lr',
            field=models.ManyToManyField(to='app.LR'),
        ),
        migrations.AddField(
            model_name='judge',
            name='permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Permission'),
        ),
        migrations.AddField(
            model_name='courtstaff',
            name='permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Permission'),
        ),
        migrations.AddField(
            model_name='casefile',
            name='court_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CourtRoom'),
        ),
        migrations.AddField(
            model_name='casefile',
            name='judges',
            field=models.ManyToManyField(to='app.Judge'),
        ),
    ]
