# Generated by Django 2.1.7 on 2019-04-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='roster',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
