# Generated by Django 2.1.7 on 2019-04-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='id',
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
