# Generated by Django 2.1.7 on 2019-04-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_casefile_roster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casefile',
            name='roster',
        ),
        migrations.AddField(
            model_name='courtroom',
            name='roster',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
