# Generated by Django 2.1.7 on 2019-04-04 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190405_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtstaff',
            name='permissions',
            field=models.ForeignKey(default='CS', on_delete=django.db.models.deletion.CASCADE, to='app.Permission'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='permissions',
            field=models.ForeignKey(default='JUDGE', on_delete=django.db.models.deletion.CASCADE, to='app.Permission'),
        ),
        migrations.AlterField(
            model_name='lr',
            name='permissions',
            field=models.ForeignKey(default='LR', on_delete=django.db.models.deletion.CASCADE, to='app.Permission'),
        ),
    ]
