# Generated by Django 2.1.7 on 2019-04-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190405_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='file',
            field=models.FileField(null=True, upload_to='files/casefiles/'),
        ),
        migrations.AddField(
            model_name='caselaw',
            name='file',
            field=models.FileField(null=True, upload_to='files/caselaws/'),
        ),
        migrations.AddField(
            model_name='legislature',
            name='file',
            field=models.FileField(null=True, upload_to='files/legislatures/'),
        ),
    ]
