# Generated by Django 2.1.7 on 2019-04-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190405_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='case_type',
            field=models.CharField(choices=[('SUPPLEMENTARY', 'Supplementary'), ('ADVANCE', 'Advance')], default='SUPPLEMENTARY', max_length=15),
        ),
    ]
