# Generated by Django 2.2 on 2019-04-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190413_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='file',
            field=models.FileField(null=True, upload_to='assets/docs/casefiles/'),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='order',
            field=models.FileField(null=True, upload_to='assets/docs/order/'),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='peshi',
            field=models.FileField(null=True, upload_to='assets/docs/peshi/'),
        ),
        migrations.AlterField(
            model_name='caselaw',
            name='file',
            field=models.FileField(null=True, upload_to='assets/docs/caselaws/'),
        ),
        migrations.AlterField(
            model_name='legislature',
            name='file',
            field=models.FileField(null=True, upload_to='assets/docs/legislatures/'),
        ),
    ]
