# Generated by Django 2.1.7 on 2019-04-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_casefile_case_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casefile',
            old_name='name',
            new_name='case_number',
        ),
        migrations.AddField(
            model_name='casefile',
            name='petitioner_advocate',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='casefile',
            name='respondant_advocate',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
