# Generated by Django 2.1.7 on 2019-04-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190405_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casefile',
            old_name='file',
            new_name='case_file',
        ),
        migrations.AddField(
            model_name='casefile',
            name='matter',
            field=models.CharField(default='N.A.', max_length=30),
        ),
        migrations.AddField(
            model_name='casefile',
            name='peshi',
            field=models.FileField(null=True, upload_to='files/peshi/'),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='petitioner_advocate',
            field=models.CharField(default='N.A.', max_length=30),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='respondant_advocate',
            field=models.CharField(default='N.A.', max_length=30),
        ),
    ]
